services:
  gradio-service:
    build: 
      context: gradio-json
      dockerfile: Dockerfile
    ports:
      - 7860:7860
    volumes:
      - /work

  backend-service:
    build:
      context: backend-json
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /code
